# Generated by Django 5.1.6 on 2025-02-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=255)),
                ('controller_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('report_program_needed', models.BooleanField(default=False)),
                ('weather_sensor_checked', models.BooleanField(default=False)),
                ('sensor_working', models.BooleanField(blank=True, null=True)),
                ('controller_status', models.CharField(choices=[('working', 'Working'), ('notWorking', 'Not Working'), ('notPresent', 'Not Present')], max_length=50)),
                ('controller_details', models.CharField(blank=True, max_length=255, null=True)),
                ('poc_info', models.CharField(choices=[('potable', 'Potable'), ('reclaimed', 'Reclaimed'), ('well', 'Well'), ('lake', 'Lake')], max_length=50)),
                ('pump_status_type', models.CharField(choices=[('pressurized', 'Pressurized'), ('pumpStart', 'Pump Start'), ('centrifugal', 'Centrifugal'), ('submersible', 'Submersible')], max_length=50)),
                ('contacted_manager', models.BooleanField(default=False)),
                ('contact_time', models.TimeField(blank=True, null=True)),
                ('communication_type', models.CharField(blank=True, choices=[('Spoke', 'Spoke'), ('Text', 'Text'), ('Voice Mail', 'Voice Mail')], max_length=250, null=True)),
                ('additional_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('start_time', models.TimeField()),
                ('seasonal_adjustment', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.irrigationreport')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.IntegerField()),
                ('zone_type', models.CharField(choices=[('Spray', 'Spray'), ('Rotor', 'Rotor'), ('MP', 'MP'), ('Drip', 'Drip'), ('Bubbler', 'Bubbler')], max_length=250)),
                ('program_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('House', 'House')], max_length=250)),
                ('power_type', models.CharField(blank=True, choices=[('Battery', 'Battery'), ('Doubler', 'Doubler')], max_length=50, null=True)),
                ('zone_faults', models.BooleanField(default=False)),
                ('checked_filters', models.BooleanField(default=False)),
                ('clogged_nozzles', models.BooleanField(default=False)),
                ('head_adjusted', models.BooleanField(default=False)),
                ('billable_repairs', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.irrigationreport')),
            ],
        ),
    ]
