# Generated by Django 5.1.6 on 2025-02-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationreport',
            old_name='controller_details',
            new_name='controller_make_model',
        ),
        migrations.RenameField(
            model_name='irrigationreport',
            old_name='contacted_manager',
            new_name='programs_needed',
        ),
        migrations.RenameField(
            model_name='irrigationreport',
            old_name='sensor_working',
            new_name='weather_sensor_working',
        ),
        migrations.RemoveField(
            model_name='irrigationprogram',
            name='report',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='communication_type',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='contact_time',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='report_program_needed',
        ),
        migrations.AddField(
            model_name='irrigationprogram',
            name='run_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='programs',
            field=models.ManyToManyField(blank=True, to='accounts.irrigationprogram'),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='additional_labor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='broken_riser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='controller_operating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='damaged_valve_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='dripline_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='head_broken_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='head_broken_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='head_raised_lowered_shrub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='head_raised_lowered_turf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='lateral_line_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='nozzle_mp_rotator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='nozzle_mpr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='rain_sensor_operating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='relocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='run_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='run_time_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='severe_line_clog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='spray_nozzle_repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='upgrade_46_popup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='upgrade_612_popup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='valve_operating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='irrigationprogram',
            name='program_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='irrigationprogram',
            name='seasonal_adjustment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationprogram',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='controller_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('notWorking', 'Not Working'), ('notPresent', 'Not Present')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='poc_info',
            field=models.CharField(blank=True, choices=[('potable', 'Potable'), ('reclaimed', 'Reclaimed'), ('well', 'Well'), ('lake', 'Lake')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationzone',
            name='program_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('House', 'House')], max_length=10),
        ),
        migrations.AlterField(
            model_name='irrigationzone',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='accounts.irrigationreport'),
        ),
        migrations.AlterField(
            model_name='irrigationzone',
            name='zone_type',
            field=models.CharField(choices=[('Spray', 'Spray'), ('Rotor', 'Rotor'), ('MP', 'MP'), ('Drip', 'Drip'), ('Bubbler', 'Bubbler')], max_length=50),
        ),
        migrations.CreateModel(
            name='AccountManagerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_manager', models.BooleanField(default=False)),
                ('contact_time', models.TimeField(blank=True, null=True)),
                ('communication_type', models.CharField(blank=True, choices=[('Spoke', 'Spoke'), ('Text', 'Text'), ('Voice Mail', 'Voice Mail')], max_length=50, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_contact', to='accounts.irrigationreport')),
            ],
        ),
    ]
