# Generated by Django 5.1.6 on 2025-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_controller_details_irrigationreport_controller_make_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationreport',
            name='programs',
        ),
        migrations.AddField(
            model_name='irrigationprogram',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.irrigationreport'),
        ),
    ]
