# Generated by Django 5.1.6 on 2025-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_irrigationzone_billable_repairs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationzone',
            old_name='upgrade_46_popup',
            new_name='upgrade_12_popup',
        ),
        migrations.RenameField(
            model_name='irrigationzone',
            old_name='upgrade_612_popup',
            new_name='upgrade_4_popup',
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='upgrade_6_popup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationzone',
            name='power_type',
            field=models.CharField(blank=True, choices=[('Battery', 'Battery'), ('Solar', 'Solar'), ('Hardwire', 'Hardwire')], max_length=50, null=True),
        ),
    ]
