# Generated by Django 5.1.6 on 2025-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_upgrade_46_popup_irrigationzone_upgrade_12_popup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationreport',
            name='pump_status_type',
            field=models.CharField(choices=[('pressurized', 'Pressurized'), ('reclaimed', 'Reclaimed'), ('pumpStart', 'Pump Start'), ('centrifugal', 'Centrifugal'), ('submersible', 'Submersible'), ('meterPoc', 'Meter POC')], max_length=50),
        ),
    ]
