# Generated by Django 5.1.6 on 2025-03-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_irrigationreport_pump_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationprogram',
            name='program_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='controller_make_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='controller_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='report_type',
            field=models.CharField(max_length=30),
        ),
    ]
