# Generated by Django 5.1.6 on 2025-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_irrigationprogram_program_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationzone',
            name='program_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
