# Generated by Django 5.1.6 on 2025-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_irrigationzone_zone_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationzone',
            name='upgrade_12_router',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='upgrade_6_router',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
