# Generated by Django 5.1.6 on 2025-03-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_irrigationzone_upgrade_12_router_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationzone',
            old_name='upgrade_12_router',
            new_name='upgrade_12_rotor',
        ),
        migrations.RenameField(
            model_name='irrigationzone',
            old_name='upgrade_6_router',
            new_name='upgrade_6_rotor',
        ),
    ]
