# Generated by Django 5.1.6 on 2025-03-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_irrigationreport_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationreport',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
