# Generated by Django 5.1.6 on 2025-03-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_irrigationreport_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranch',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
    ]
